ktor:
  application:
    modules:
      - ktor.ApplicationKt.module
  deployment:
    port: 8081
    host: "0.0.0.0"
  database:
    url: "jdbc:postgresql://localhost:5433/euroexplorer"
    driver: "org.postgresql.Driver"
    username: "postgres"
    password: "josema16"